name: Process-PSModule

on:
  workflow_call:

jobs:
  Get-PSModule:
    name: Get-PSModule
    runs-on: ubuntu-latest
    steps:
      - name: 'Get parameter file paths'
        id: Get-PSModule
        shell: pwsh
        run: |
          # Get-PSModule
          Write-Output "##[group]Get-PSModule"
          $srcPath = (Join-Path $env:GITHUB_WORKSPACE 'src')
          $moduleFolders = @()
          $moduleFolders += Get-ChildItem -Path $srcPath -Directory | Select-Object -ExpandProperty FullName
          $moduleFolders = $moduleFolders | ConvertTo-Json -AsArray -Compress
          Write-Verbose "PSModules=$moduleFolders" -Verbose
          Write-Output "PSModules=$moduleFolders" >> $env:GITHUB_OUTPUT
          Write-Output "##[endgroup]"
    outputs:
      PSModules: ${{ steps.Get-PSModule.outputs.PSModules }}

  Process-PSModule:
    name: Process-PSModule
    runs-on: ubuntu-latest
    needs:
      - Get-PSModule
    strategy:
      fail-fast: false
      matrix:
        PSModule: ${{ fromJson(needs.Get-PSModule.outputs.PSModules) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # - name: Initialize-PSModule
      #   uses: PSModule/Initialize-PSModule@main
      #   with:
      #     Version: $null

      # - name: Build-PSModule
      #   uses: PSModule/Build-PSModule@main

      # - name: Test-PSModule
      #   uses: PSModule/Test-PSModule@main

      # - name: Release-PSModule
      #   uses: PSModule/Release-PSModule@main
      #   with:
      #     APIKey: ${{ secrets.APIKEY }}
      #   env:
      #     GH_TOKEN: ${{ github.token }} # Used for GitHub CLI authentication
