name: Process-PSModule

on:
  workflow_call:
    secrets:
      APIKey:
        required: true

jobs:
  Get-PSModuleNames:
    name: Get-PSModuleNames
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: 'Get-PSModuleNames'
        id: Get-PSModuleNames
        shell: pwsh
        run: |
          # Get-PSModuleNames
          Write-Output "##[group]Get-PSModuleNames"
          $srcPath = (Join-Path $env:GITHUB_WORKSPACE 'src')
          $moduleNames = @()
          $moduleNames += Get-ChildItem -Path $srcPath -Directory | Select-Object -ExpandProperty Name
          $moduleNames = $moduleNames | ConvertTo-Json -AsArray -Compress
          Write-Verbose "ModuleNames=$moduleNames" -Verbose
          Write-Output "ModuleNames=$moduleNames" >> $env:GITHUB_OUTPUT
          Write-Output "##[endgroup]"
    outputs:
      ModuleNames: ${{ steps.Get-PSModule.outputs.ModuleNames }}

  Process-PSModule:
    name: Process-PSModule
    runs-on: ubuntu-latest
    needs:
      - Get-PSModuleNames
    strategy:
      fail-fast: false
      matrix:
        ModuleName: ${{ fromJson(needs.Get-PSModuleNames.outputs.ModuleNames) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Initialize-PSModule
        uses: PSModule/Initialize-PSModule@main

      - name: Build-PSModule
        uses: PSModule/Build-PSModule@main
        with:
          Name: ${{ matrix.ModuleName }}

      - name: Test-PSModule
        uses: PSModule/Test-PSModule@main
        with:
          Name: ${{ matrix.ModuleName }}

      - name: Release-PSModule
        uses: PSModule/Release-PSModule@main
        with:
          APIKey: ${{ secrets.APIKEY }}
          Name: ${{ matrix.ModuleName }}
        env:
          GH_TOKEN: ${{ github.token }} # Used for GitHub CLI authentication
